[project]
name = "signals"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "Trevor Manz", email = "trevor.j.manz@gmail.com" }
]
dependencies = []
readme = "README.md"
requires-python = ">= 3.8"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = [
    "pytest>=8.1.2",
    "ipython>=8.24.0",
    "jupyterlab>=4.2.0",
    "ipywidgets>=8.1.2",
]

[tool.hatch.metadata]
allow-direct-references = true

[tool.ruff.lint]
pydocstyle = { convention = "numpy" }
select = [
        "E",    # style errors
        "W",    # style warnings
        "F",    # flakes
        "D",    # pydocstyle
        "D417", # Missing argument descriptions in Docstrings
        "I",    # isort
        "UP",   # pyupgrade
        "C4",   # flake8-comprehensions
        "B",    # flake8-bugbear
        "A001", # flake8-builtins
        "RUF",  # ruff-specific rules
        "TCH",  # flake8-type-checking
        "TID",  # flake8-tidy-imports
]

[tool.ruff.lint.per-file-ignores]
"tests/*.py" = ["D", "S"]
"src/signals/__init__.py" = ["F401"]
