name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Lint:
    runs-on: macos-14
    if: github.repository == 'manzt/signals'

    steps:
      - uses: actions/checkout@v4
      - run: |
          curl -LsSf https://astral.sh/uv/0.3.0/install.sh | sh
      - run: uv run ruff check

  Test:
    runs-on: macos-14
    if: github.repository == 'manzt/signals'

    steps:
      - uses: actions/checkout@v4
      - run: |
          curl -LsSf https://astral.sh/uv/0.3.0/install.sh | sh
      - run: uv run pytest
